name: Build and Deploy Angular App

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build the Angular project
      - name: Build Angular Project
        run: npm run build -- --output-path=dist/angular18/ --base-href /angular18/

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ANGU_TOKEN }}
          publish_dir: ./dist/angular18/browser

  docker_build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: docker build -t angular18-app .

      # Step 3: Run Docker Container (Optional: for testing)
      - name: Run Docker Container
        run: docker run -d -p 8080:80 angular18-app
